### ISSUE TITLE
Question: What are these lines doing?

### ISSUE THREAD

**Issue by razic** [jmhale/okta-awscli#111]
Hey, I'm just curious what these lines of code are for?

https://github.com/jmhale/okta-awscli/blob/b85dd963853bb90006ac637e795ff258d5bae306/oktaawscli/okta_auth.py#L271-L273

**Comment by jmhale** [comment]
These were added for the per-app MFA support in #107. 

Tagging @nonspecialist. Do you know what these cookies are set for? Admittedly, I haven't given them much thought.

**Comment by jmhale** [comment]
I cannot figure out what these are for or find any documentation on their purpose.

Removing them from being set doesn't seem to affect the current functionality. They're removed in the current `develop` and will be gone in `v0.4.3`.

Thanks for raising this! Closing.
