### ISSUE TITLE
"app-link" - what is this?

### ISSUE THREAD

**Issue by elice02** [jmhale/okta-awscli#117]
Is there any documentation anywhere what the 'app-link' is?

app-link = <app_link_from_okta> # Found in Okta's configuration for your AWS account.****

When I google okta 'app-link' or 'okta application link' nothing comes up. I don't have access to Okta's configuration information so I need to ask for the app link from the client, but as there's no real information what this means or even is, it's a bit difficult for me to ask for it.

Is this something that's required? Does this application interactively request it from me when running? So far, all I'm getting is 'authentication failed' errors and no information as to why via debug.

**Comment by neelakansha85** [comment]
You can find this from your OKTA UI. When you login to your home page of OKTA UI, right click your amazon app and select "Copy link address". Remove query parameters if any in the url such as `?fromHome=true` from the complete url `https://<YOUR_COMPANY>.okta.com/home/amazon_aws/<UNIQUE_ID>/<APP_ID>?fromHome=true`
