### ISSUE TITLE
Expired passwords are not gracefully handled

### ISSUE THREAD

**Issue by arahayrabedian** [jmhale/okta-awscli#119]
**Describe the bug**
Expired password leads to an exception with a KeyError stack trace (not sure if it'd behave the same with other organizations)

**To Reproduce**
1. When your (okta) password is expired and you use two factor auth (not sure of behaviour with other second factors)
1. attempt to retrieve new aws credentials
1. KeyError trying to get a key (I think it was `id`) in the response (sorry i lost the stack trace, but will update if i manage to get it)

**Expected behavior**
A message indicating that your password is expired

**Output**
unfortunately lost this, but will try to reproduce at a later point.

**Environment (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS, etc.]
   - ubuntu 18.04.03
 - Version of okta-awscli you're running. `okta-awscli -V`
   - 0.4.0

**Additional context**
EOM

**Comment by jmhale** [comment]
I believe this has been fixed by some unrelated changes around logging. I just expired one of my test users and I'm getting back and cleaner `ERROR - Authentication failed` message.

I'm going to close this, but please feel free to re-raise if it's still being problematic.
