### ISSUE TITLE
Don't always save the role

### ISSUE THREAD

**Issue by thenoid** [jmhale/okta-awscli#125]
**Is your feature request related to a problem? Please describe.**
https://github.com/jmhale/okta-awscli/blob/ceeab286525bc4be78e703932dc3f41024cc4419/oktaawscli/okta_awscli.py#L23

The script assumes that you want to save the role that you select and then doesn't prompt upon further invocations.  Maybe I want to choose a different role and different times.  It would be nice to have that option without having to edit the dot file

**Describe the solution you'd like**
Add a command-line option and a config option to not save the role
`--no-save-role` or
```
no-save-role = true
```

**Describe alternatives you've considered**
All other alternatives involve munging the config file, which sucks.
`perl -p -i -e 's/role = .*//g' ~/.okta-aws` etc

**Comment by jmhale** [comment]
Fixed in `v0.4.2`

**Comment by thoroc** [comment]
Sorry to jump late on this ticket, but does the behaviour no ignore the role in the config file now?

Just asking as I have now to pick the role despite having it configured in the `.okta-awscli` file, which is made even awkward since the returned roles are not in any orders (I have 20+ assigned to me by my org).

**Comment by jmhale** [comment]
@thoroc if you don't have the `--force` flag set, then you shouldn't be prompted to choose a role, so long as you have one set in your `.okta-aws` file. 

I just tested and confirmed that to be the case with the latest version, `0.4.6`.

Are you seeing behavior that is different?

**Comment by thoroc** [comment]
@jmhale just updated to version 0.4.6, and I am not being prompted to pick a role already defined in the `okta-aws` config file. I can confirm the behaviour observed with the previous (0.4.5) version isn't there anymore, and it is working as expected.

Thank you.
~TR
