### ISSUE TITLE
Support MFA code as parameter

### ISSUE THREAD

**Issue by jafrouk** [jmhale/okta-awscli#13]
Some users may want to run the script without the need for any interactive prompts. This could be supported by https://github.com/jmhale/okta-awscli/issues/3, https://github.com/jmhale/okta-awscli/issues/4, https://github.com/jmhale/okta-awscli/issues/12 and one final addition:

Add an optional parameter --mfa_code (supported only if the factor choice is specified in config) where the use can specify this on the command and avoid all interactive prompts

**Comment by jmhale** [comment]
Fixed in #25
