### ISSUE TITLE
Expired AWS GovCloud tokens are not recognized as needing refreshed

### ISSUE THREAD

**Issue by mrbcmorris** [jmhale/okta-awscli#136]
**Describe the bug**
When an AWS GovCloud token expires, `okta-awscli` reports `INFO - STS credentials are valid. Nothing to do.` 

**To Reproduce**
1. Request a govcloud token
2. Allow it to expire
3. Try to acquire new token via `okta-awscli` with debug turned on 
4. See `okta-awscli` reports `INFO - STS credentials are valid. Nothing to do.` 

**Expected behavior**
`okta-awscli` prompts the user for credentials and requests a new token

**Output**
```
± okta-awscli --okta-profile {oktaProfile} --profile {profile} -d
DEBUG - Setting AWS role to {roleArn}
INFO - STS credentials are valid. Nothing to do.
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Version of okta-awscli you're running. `okta-awscli -V` : `0.4.1`

**Additional context**
Default aws credentials are for `us-west-2`.  Changing to `us-gov-east-1` did not resolve.

------

:wave: Hey folks, I've been using `okta-awscli` successfully against the standard aws partition for a few months now and started encountering this strange behavior when using the tool to authenticate to AWS GovCloud.  At first, my resolution was to delete the profile created in `~/.aws/credentials` (but now I know there's a `--force` command!).  After getting frustrated, I decided to look deeper and found what appears to be a mishandling of the GovCloud partition when checking if a token is still valid.

I have created a patch that was able to resolve the issue for me and I'll submit a PR shortly.  Let me know if there's any other information I can provide.

Cheers!

**Comment by jmhale** [comment]
Released in `v0.4.3`. Thanks!
