### ISSUE TITLE
~/.okta-aws [profile] role value not preventing role selection user input

### ISSUE THREAD

**Issue by cqwense** [jmhale/okta-awscli#150]
**Describe the bug**
the role = value from my ~/.okta-aws file is not preventing okta-awscli from asking me to select a role from the available list, though debug does show it is read prior to the selection step.

**To Reproduce / Environment **

 > okta-awscli --version
0.4.6
--
 > aws --version
aws-cli/2.1.1 Python/3.9.0 Darwin/18.7.0 source/x86_64
--
 > python --version
Python 3.9.0

my okta-awscli config file: 

> cat ~/.okta-aws

[XXX-dev]
base-url = okta.xxxxx.com
factor = GOOGLE
app-link = https://okta.xxx.com/home/amazon_aws/XXXX/XXX
duration = 14400
role = arn:aws:iam::12345:role/vgr-devops

[XXX-qa]
base-url = okta.xxxxx.com
factor = GOOGLE
app-link = https://okta.xxx.com/home/amazon_aws/XXXX/XXX
duration = 14400
role = arn:aws:iam::54321:role/vgr-devops

[XXX-prod]
base-url = okta.xxxxx.com
factor = GOOGLE
app-link = https://okta.xxx.com/home/amazon_aws/XXXX/XXX
duration = 14400
role = arn:aws:iam::15243:role/vgr-devops

--

**Output**

> okta-awscli --debug -v --okta-profile xxx-dev --profile default --force
DEBUG - Setting AWS role to arn:aws:iam::12345:role/vgr-devops
DEBUG - Setting AWS partition to AwsPartition.AWS
DEBUG - Checking STS token against ARN partition: AwsPartition.AWS
INFO - STS credentials are valid. Nothing to do.
INFO - Force option selected,                 getting new credentials anyway.
DEBUG - Setting MFA factor to GOOGLE
INFO - App Link set as: https://okta.xxx.com/home/amazon_aws/XXXXXX/XXX
INFO - Authenticating to: okta.xxx.com
Enter username: xxxxx
Enter password:
DEBUG - {'id': 'XXXXX', 'factorType': 'token:software:totp', 'provider': 'GOOGLE', 'vendorName': 'GOOGLE', 'profile': {'credentialId': 'xxxx@xxxx.net'}, '_links': {'verify': {'href': 'https://okta.XXXXX.com/api/v1/authn/factors/XXXXX/verify', 'hints': {'allow': ['POST']}}}}
Enter MFA verification code: XXXXXX
INFO - Refreshing role
INFO - Please choose a role.
1: arn:aws:iam::12345:role/vgr-devops
2: arn:aws:iam::54321:role/vgr-devops
3: arn:aws:iam::15243:role/vgr-devops
Please select the AWS role:

**Comment by cqwense** [comment]
https://github.com/jmhale/okta-awscli/issues/125
&
https://github.com/jmhale/okta-awscli/issues/122

doing a bit more research i'm guessing these are what broke my use case, I ran --force, and always used --profile default so I didn't have to go editing my aws cli commands with profile arguments.

I can work around it and/or go back to 0.4.1 for the time being, but maybe an argument/config about whether to save roles through a --force is a better option , instead of one or the other.

**Comment by rrhodes** [comment]
Also experiencing this issue with version 0.4.6. Downgrading to 0.4.0 (as known working version) is a temporary workaround in my case. Not explored other versions yet, but happy to do so shortly and report back with further details in my case.

**Comment by jmhale** [comment]
@cqwense and @rrhodes Thanks for calling this out, and apologies for the delay in responding.

Breaking up the functionality into two flags makes sense to me. @rrhodes looking at your PR now.

**Comment by jmhale** [comment]
Fix released in `0.5.0`. Thanks!
