### ISSUE TITLE
Support AWS role choice in config

### ISSUE THREAD

**Issue by jmhale** [jmhale/okta-awscli#4]
If an org has multiple AWS roles configured, the user may only use one on a regular basis, and having to select it every time can get annoying.

We should support pre-selecting this in the profile defined in ~/.okta-aws

Maybe also have a --prompt flag to override this on a per-execution basis and prompt for which role to use. (Similar to what is proposed in #3)

**Comment by jmhale** [comment]
Added to v0.2.0 in #15

**Comment by jafrouk** [comment]
I created a pull request to add this to README, but also - did you implement a --prompt flag?

**Comment by jmhale** [comment]
@jafrouk I didn't implement that as part of this issue. That was more of me thinking out loud, rather than proposing it to be included in the scope of the issue.

If it's something that people would use, then we can open a new issue to request the feature.
