### ISSUE TITLE
Feature request: ability to provide a way to map account id to an alias

### ISSUE THREAD

**Issue by bkruger99** [jmhale/okta-awscli#5]
Looking at the return saml, if you want to keep a same role name across the board, you end up with a screen of role names.  Add several accounts and you're playing spin the wheel to figure out what account you're using.

Proposing either id=alias mapping in the default config or ability to specify a yaml/json/whatever file which is more or less account:alias, one per line.  Yaml would probably be my first choice for ease of eyeballing/editing.  Specifying the file to read would be done in the config file.

If you want to get extra fancy, another field could be added to give a profile name to use as well, which opens up possibility for "always force profile" to be an option, etc..

Will try to get a pull request submitted for this soon.

**Comment by jmhale** [comment]
I'm going to close this, since I think that with the addition of the `app-link` in #54, I think the spirit of the request is satisfied.
