### ISSUE TITLE
Prompt user paswrod rather than saving it in .okta-aws file

### ISSUE THREAD

**Issue by allieliongpailui** [jmhale/okta-awscli#53]
Is there any way to prevent the user password from being saved in .okta-aws file but to be prompted during login?
Thanks

Allie

**Comment by jmhale** [comment]
Yes, simply omitting the password parameter from `~/.okta-aws` will cause okta-awscli to prompt the user for the password in the console.

This is actually the default and preferred action. The ability to store the user password in the config file is not recommended unless you're really sure of what you're doing (as called out in the example config in the README)
