### ISSUE TITLE
Cache credentials for future use

### ISSUE THREAD

**Issue by justinm** [jmhale/okta-awscli#7]
To supplement #6, it'd be nice to also have a way to more easily authenticate more terminals than just one.

**New flags**: `--use-cache`

**User Authentication Workflow**
--------

- User authenticates via `okta-awscli`
- okta-awscli saves credentials to ~/.kube/okta-awscli.credentials each time
- User runs `okta-awscli --use-cache` on each terminal
  - If credentials are cached
    - okta-awscli re-exports the cached credentials
    - okta-awscli exits with status code 0
  - If credentials are not cached
    - okta-awscli re-exports the cached credentials
    - okta-awscli exits with status code -1

**Automated Workflow**
--------

- User authenticates via `okta-awscli`
- okta-awscli saves credentials to ~/.kube/okta-awscli.credentials each time
- User prepends `okta-awscli --use-cache` to each script
  - If credentials are cached
    - okta-awscli re-exports the cached credentials
    - okta-awscli exits with status code 0
  - If credentials are not cached
    - okta-awscli re-exports the cached credentials
    - okta-awscli exits with status code -1
- Example: `okta-awscli --use-cache`

**Comment by jmhale** [comment]
Fixed in #25
