### ISSUE TITLE
Storing region in shared credentials file overwrites profile settings in config.

### ISSUE THREAD

**Issue by SirFerdek** [jmhale/okta-awscli#72]
**Describe the bug**
I have an account, which I want to use in us-west-2 region. After authentication with okta-awscli, us-east-1 region gets written to .aws/credentials. This overwrites my settings in .aws/config, which now I have to overwrite in other way.

Simply removing the 'region' line in .aws/credentials solves the problem for me.

**To Reproduce**
1. authenticate with profile name specified
2. launch aws-shell or aws-cli
3. check that region might be different for what you set in .aws/config

**Expected behavior**
I can store my preferred region for profile in .aws/config and it will work with aws-shell after authentication.

**Environment (please complete the following information):**
 - OS: Debian
 - okta-cli version 0.2.5

**Comment by SirFerdek** [comment]
Might be related to #19 in broader perspective.

**Comment by jmhale** [comment]
Fixed in v0.3.1
